#!/usr/bin/env python3
"""Generate core/z8000/z8002.c from MAME's z8000ops.hxx and z8000tbl.hxx.

The result is a plain-C Z8002 (non-segmented) core operating on a global state
pointer `Z`, so several CPUs can share one copy of the code. Memory and I/O go
through z8k_rb/z8k_rw/z8k_wb/z8k_ww/z8k_in/z8k_out supplied by the machine.
"""
import re, sys
from pathlib import Path

src = Path(sys.argv[1])
out = Path(sys.argv[2])
# opcode handlers that should live in fast memory on the target (profiled with Z8K_PROFILE)
hot_file = out.parent / 'hot_ops.txt'
hot = set(hot_file.read_text().split()) if hot_file.exists() else set()
ops = (src / 'z8000ops.hxx').read_text()
tbl = (src / 'z8000tbl.hxx').read_text()

def strip_logs(text):
    lines = text.split('\n'); res = []; skip = False
    for ln in lines:
        st = ln.strip()
        if skip:
            if st.endswith(');'): skip = False
            continue
        if st.startswith('LOG(') or st.startswith('logerror(') or st.startswith('LOGMASKED('):
            if not st.endswith(');'): skip = True
            continue
        res.append(ln)
    return '\n'.join(res)

ops = strip_logs(ops)
ops = '\n'.join(l for l in ops.split('\n') if 'printf(' not in l)   # debug prints about segmented mode
# drop the Z8001 (segmented) variants entirely
ops = re.sub(r'^(?:uint\d+_t|int\d+_t|void|bool)\s+z8001_device::\w+\([^)]*\)\s*\{.*?^\}', '', ops, flags=re.M | re.S)
# block-transfer ops pick an address space; there is only one here
ops = re.sub(r'^\s*memory_access<[^>]*>::specific\s*&(\w+)\s*=[^;]*;', r'\tint \1 = 0; (void)\1;', ops, flags=re.M)
# member function definitions -> static functions (hot ones get the Z8K_HOT placement attribute)
def _fn(m):
    ret, name = m.group(1), m.group(2)
    attr = 'Z8K_HOT ' if name in hot else ''
    return f'static {attr}{ret} {name}('
ops = re.sub(r'^(uint8_t|uint16_t|uint32_t|uint64_t|int8_t|int16_t|int32_t|void|bool)\s+z8002_device::(\w+)\(', _fn, ops, flags=re.M)
# spaces passed to RDMEM/WRMEM become dummy args
ops = re.sub(r'\bm_(data|program|stack|io|sio)\b', '0', ops)
ops = ops.replace('reg == SP ? 0 : 0', '0')
ops = re.sub(r'm_(cache|opcache)\.read_word\(', 'z8k_rw(', ops)
# state members
ops = re.sub(r'\bm_(\w+)', r'Z->\1', ops)
ops = ops.replace('get_segmented_mode()', '0')
ops = ops.replace('F_SEG_Z8001()', '0')
ops = ops.replace('PSA_ADDR()', '(Z->psapoff)')
ops = re.sub(r'Z->irq_vec = Z->iack_in\[\d\]\(Z->pc\);', 'Z->irq_vec = 0xffff;', ops)
ops = re.sub(r'Z->(mo_out|ns_out|busack_out)\([^;]*\);', ';', ops)
ops = re.sub(r'standard_irq_callback\([^;]*\);', ';', ops)
ops = re.sub(r'\bassert\s*\([^;]*\);', ';', ops)
ops = re.sub(r'\bBIT\(([^,()]+(?:\([^()]*\))?[^,()]*),\s*([^()]+)\)', r'((((\1) >> (\2)) & 1))', ops)
ops = ops.replace('(void)0;', ';')
ops = ops.replace('()const', '(void)')
ops = re.sub(r'(static void zinvalid\(\)\s*\{)', r'\1 z8k_invalid_count++;', ops)

# table
names = re.findall(r'&z8002_device::(\w+)', tbl)
tbl = re.sub(r'&z8002_device::(\w+)', r'\1', tbl)
tbl = tbl.replace('const z8002_device::Z8000_init z8002_device::table[] =', 'static Z8000_init table[] =')  # non-const so it lands in RAM
tbl = strip_logs(tbl).replace('nullptr', '0')

header = r'''/*
 * z8002.c - Zilog Z8002 CPU core, GENERATED by tools/gen_z8002.py from MAME's
 * src/devices/cpu/z8000/z8000ops.hxx, z8000tbl.hxx and z8000.cpp
 * (BSD-3-Clause, copyright Juergen Buchmueller, Ernesto Corvi and the MAME team).
 * Do not edit; regenerate. Non-segmented Z8002 only.
 */
#include "z8002.h"
#include <string.h>
#include <stdio.h>
#include <stdbool.h>
#ifndef Z8K_HOT
#define Z8K_HOT            /* placement attribute for hot handlers (IRAM_ATTR on the ESP32) */
#endif
#ifndef Z8K_DATA
#define Z8K_DATA           /* placement attribute for the dispatch tables (DRAM_ATTR on the ESP32: the
                              compiler would otherwise move these never-written statics into flash rodata) */
#endif

static z8k_t Zs;               /* the CPU being run; z8k_run copies the caller's state in and out */
#define Z (&Zs)
uint32_t z8k_invalid_count;
#ifdef Z8K_PROFILE
uint32_t z8k_op_count[600];
const char *z8k_op_name(int i);
#endif

typedef void (*opcode_func_t)(void);
static Z8K_DATA uint8_t z8000_zsp[256];
/* opcode -> table index, as 16-entry blocks (deduplicated) so it lives in RAM; see the end of this file */
static uint16_t z8000_exec_idx[0x1000];
static uint16_t z8000_exec_blk[];
static opcode_func_t z8000_exec_fn[];
static uint16_t z8000_exec_cyc[];
#define Z8000_EXEC(op) (z8000_exec_blk[(z8000_exec_idx[(op) >> 4] << 4) | ((op) & 15)])
#ifdef Z8K_PROFILE
extern uint32_t z8k_op_count[600];
#endif

/* Fast memory path: the machine publishes 256-entry page tables of native-endian
 * 16-bit words for the active CPU. The read table must map every page (filler for unmapped);
 * NULL write pages fall back to z8k_ww()/z8k_wb(). */
const uint16_t *const *z8k_rpage;
uint16_t *const *z8k_wpage;
/* Reads always go through the table (the machine maps every page, unmapped ones to a filler page)
 * so that the opcode handlers are leaf functions. */
static inline uint16_t z8k_rw_fast(uint32_t a)
{
    return z8k_rpage[(a >> 8) & 0xff][(a & 0xff) >> 1];
}
static inline uint8_t z8k_rb_fast(uint32_t a)
{
    uint16_t w = z8k_rpage[(a >> 8) & 0xff][(a & 0xff) >> 1];
    return (a & 1) ? (uint8_t)w : (uint8_t)(w >> 8);
}
static inline void z8k_ww_fast(uint32_t a, uint16_t v)
{
    uint16_t *p = z8k_wpage[(a >> 8) & 0xff];
    if (p) p[(a & 0xff) >> 1] = v; else z8k_ww(a, v);
}
static inline void z8k_wb_fast(uint32_t a, uint8_t v)
{
    uint16_t *p = z8k_wpage[(a >> 8) & 0xff];
    if (p) { uint16_t *w = &p[(a & 0xff) >> 1]; *w = (a & 1) ? (uint16_t)((*w & 0xff00) | v) : (uint16_t)((*w & 0x00ff) | (v << 8)); }
    else z8k_wb(a, v);
}

#define BYTE_XOR_BE(a)  ((a) ^ 1)
#define BYTE4_XOR_BE(a) ((a) ^ 3)
#define BYTE8_XOR_BE(a) ((a) ^ 7)
#define RB(n)   Z->regs.B[BYTE8_XOR_BE((((n) & 7) << 1) | (((n) & 8) >> 3))]
#define RW(n)   Z->regs.W[BYTE4_XOR_BE(n)]
#define RL(n)   Z->regs.L[BYTE_XOR_BE((n) >> 1)]
#define RQ(n)   Z->regs.Q[(n) >> 2]
#define SP      15
#define RST     ((Z->psapoff) + 0)
#define EPU     ((Z->psapoff) + 0x0004)
#define TRAP    ((Z->psapoff) + 0x0008)
#define SYSCALL ((Z->psapoff) + 0x000c)
#define SEGTRAP ((Z->psapoff) + 0x0010)
#define NMI     ((Z->psapoff) + 0x0014)
#define NVI     ((Z->psapoff) + 0x0018)
#define VI      ((Z->psapoff) + 0x001c)
#define VEC00   ((Z->psapoff) + 0x001e)
#define Z8000_EPU     0x80
#define Z8000_TRAP    0x40
#define Z8000_NMI     0x20
#define Z8000_SEGTRAP 0x10
#define Z8000_NVI     0x08
#define Z8000_VI      0x04
#define Z8000_SYSCALL 0x02
#define Z8000_RESET   0x01
#define F_SEG   0x8000
#define F_S_N   0x4000
#define F_EPU   0x2000
#define F_VIE   0x1000
#define F_NVIE  0x0800
#define F_C     0x0080
#define F_Z     0x0040
#define F_S     0x0020
#define F_PV    0x0010
#define F_DA    0x0008
#define F_H     0x0004
#define OP0 0
#define OP1 1
#define OP2 2
#define NIB0 12
#define NIB1 8
#define NIB2 4
#define NIB3 0
#define S08 0x80
#define S16 0x8000
#define S32 0x80000000
#define GET_C  ((Z->fcw >> 7) & 1)
#define GET_Z  ((Z->fcw >> 6) & 1)
#define GET_S  ((Z->fcw >> 5) & 1)
#define GET_PV ((Z->fcw >> 4) & 1)
#define GET_DA ((Z->fcw >> 3) & 1)
#define GET_H  ((Z->fcw >> 2) & 1)
#define CLR_C  Z->fcw &= ~F_C
#define CLR_Z  Z->fcw &= ~F_Z
#define CLR_S  Z->fcw &= ~F_S
#define CLR_P  Z->fcw &= ~F_PV
#define CLR_V  Z->fcw &= ~F_PV
#define CLR_DA Z->fcw &= ~F_DA
#define CLR_H  Z->fcw &= ~F_H
#define CLR_CZS   Z->fcw &= ~(F_C|F_Z|F_S)
#define CLR_CZSP  Z->fcw &= ~(F_C|F_Z|F_S|F_PV)
#define CLR_CZSV  Z->fcw &= ~(F_C|F_Z|F_S|F_PV)
#define CLR_CZSVH Z->fcw &= ~(F_C|F_Z|F_S|F_PV|F_H)
#define CLR_ZS    Z->fcw &= ~(F_Z|F_S)
#define CLR_ZSV   Z->fcw &= ~(F_Z|F_S|F_PV)
#define CLR_ZSP   Z->fcw &= ~(F_Z|F_S|F_PV)
#define SET_C  Z->fcw |= F_C
#define SET_Z  Z->fcw |= F_Z
#define SET_S  Z->fcw |= F_S
#define SET_P  Z->fcw |= F_PV
#define SET_V  Z->fcw |= F_PV
#define SET_DA Z->fcw |= F_DA
#define SET_H  Z->fcw |= F_H
#define SET_SC Z->fcw |= F_C | F_S
#define CC0 (0)
#define CC1 (GET_PV^GET_S)
#define CC2 (GET_Z|(GET_PV^GET_S))
#define CC3 (GET_Z|GET_C)
#define CC4 GET_PV
#define CC5 GET_S
#define CC6 GET_Z
#define CC7 GET_C
#define CC8 (1)
#define CC9 !(GET_PV^GET_S)
#define CCA !(GET_Z|(GET_PV^GET_S))
#define CCB !(GET_Z|GET_C)
#define CCC !GET_PV
#define CCD !GET_S
#define CCE !GET_Z
#define CCF !GET_C
#define GET_BIT(o)      uint16_t bit = 1 << (get_operand(o) & 15)
#define GET_CCC(o,s)    uint8_t cc = (get_operand(o) >> (s)) & 15
#define GET_DST(o,s)    uint8_t dst = (get_operand(o) >> (s)) & 15
#define GET_SRC(o,s)    uint8_t src = (get_operand(o) >> (s)) & 15
#define GET_IDX(o,s)    uint8_t idx = (get_operand(o) >> (s)) & 15
#define GET_CNT(o,s)    int8_t cnt = (get_operand(o) >> (s)) & 15
#define GET_IMM4(o,s)   uint8_t imm4 = (get_operand(o) >> (s)) & 15
#define GET_I4M1(o,s)   uint8_t i4p1 = ((get_operand(o) >> (s)) & 15) + 1
#define GET_IMM1(o,s)   uint8_t imm1 = (get_operand(o) >> (s)) & 2
#define GET_IMM2(o,s)   uint8_t imm2 = (get_operand(o) >> (s)) & 3
#define GET_IMM3(o,s)   uint8_t imm3 = (get_operand(o) >> (s)) & 7
#define GET_IMM8(o)     uint8_t imm8 = (uint8_t)get_operand(o)
#define GET_IMM16(o)    uint16_t imm16 = get_operand(o)
#define GET_IDX16(o)    uint32_t idx16 = get_operand(o)
#define GET_IMM32       uint32_t imm32 = get_operand(1); imm32 = (imm32 << 16) + get_operand(2)
#define GET_DSP7        uint8_t dsp7 = get_operand(0) & 127
#define GET_DSP8        int8_t dsp8 = (int8_t)get_operand(0)
#define GET_DSP16       uint16_t tmp16 = get_operand(1); uint32_t dsp16 = addr_add(Z->pc, (int16_t)tmp16)
#define GET_ADDR(o)     uint32_t addr = (uint32_t)get_addr_operand(o)
#define GET_ADDR_RAW(o) uint32_t addr = (uint32_t)get_raw_addr_operand(o)
#define CLEAR_LINE 0
#define ASSERT_LINE 1

/* bus: the space argument from MAME is ignored (Z8002 has one address space here) */
#define RDMEM_B(sp, a)    z8k_rb_fast((a) & 0xffff)
#define RDMEM_W(sp, a)    z8k_rw_fast((a) & 0xfffe)
#define RDMEM_L(sp, a)    (((uint32_t)z8k_rw_fast((a) & 0xfffe) << 16) | z8k_rw_fast(((a) + 2) & 0xfffe))
#define WRMEM_B(sp, a, v) z8k_wb_fast((a) & 0xffff, (uint8_t)(v))
#define WRMEM_W(sp, a, v) z8k_ww_fast((a) & 0xfffe, (uint16_t)(v))
#define WRMEM_L(sp, a, v) do { z8k_ww_fast((a) & 0xfffe, (uint16_t)((v) >> 16)); z8k_ww_fast(((a) + 2) & 0xfffe, (uint16_t)(v)); } while (0)
#define RDPORT_B(m, a)    z8k_in((a))
#define RDPORT_W(m, a)    ((uint16_t)((z8k_in((a)) << 8) | z8k_in((a) + 1)))
#define WRPORT_B(m, a, v) z8k_out((a), (uint8_t)(v))
#define WRPORT_W(m, a, v) do { z8k_out((a), (uint8_t)((v) >> 8)); z8k_out((a) + 1, (uint8_t)(v)); } while (0)
#define cycles(n) (Z->icount -= (n))

static inline uint32_t addr_add(uint32_t addr, uint32_t addend) { return (addr & 0xffff0000) | ((addr + addend) & 0xffff); }
static inline uint32_t addr_sub(uint32_t addr, uint32_t s) { return (addr & 0xffff0000) | ((addr - s) & 0xffff); }
static inline uint16_t RDOP(void) { uint16_t r = z8k_rw_fast(Z->pc & 0xfffe); Z->pc += 2; return r; }
static inline uint32_t get_operand(int opnum)
{
    if (opnum == 0) return Z->op[0];       /* always fetched by the run loop */
    if (!(Z->op_valid & (1 << opnum))) { Z->op[opnum] = z8k_rw_fast(Z->pc & 0xfffe); Z->pc += 2; Z->op_valid |= (1 << opnum); }
    return Z->op[opnum];
}
#define get_addr_operand(o) get_operand(o)
#define get_raw_addr_operand(o) get_operand(o)

'''

protos = '\n'.join(f'static void {n}(void);' for n in dict.fromkeys(names))

interrupt = r'''
static void PUSH_PC(void) { PUSHW(SP, Z->pc); }
static uint32_t GET_PC(uint32_t VEC) { return RDMEM_W(0, VEC + 2); }
static uint16_t GET_FCW(uint32_t VEC) { return RDMEM_W(0, VEC); }

static void Interrupt(void)
{
    uint16_t fcw = Z->fcw;
    if (Z->irq_req & Z8000_RESET) {
        Z->pc = RDMEM_W(0, 4);
        Z->irq_req &= Z8000_NVI | Z8000_VI;
        CHANGE_FCW(RDMEM_W(0, 2));
    } else if (Z->irq_req & Z8000_EPU) {
        CHANGE_FCW(fcw | F_S_N); PUSH_PC(); PUSHW(SP, fcw); PUSHW(SP, Z->op[0]);
        Z->pc = GET_PC(EPU); Z->irq_req &= ~Z8000_EPU; CHANGE_FCW(GET_FCW(EPU));
    } else if (Z->irq_req & Z8000_TRAP) {
        CHANGE_FCW(fcw | F_S_N); PUSH_PC(); PUSHW(SP, fcw); PUSHW(SP, Z->op[0]);
        Z->pc = GET_PC(TRAP); Z->irq_req &= ~Z8000_TRAP; CHANGE_FCW(GET_FCW(TRAP));
    } else if (Z->irq_req & Z8000_SYSCALL) {
        CHANGE_FCW(fcw | F_S_N); PUSH_PC(); PUSHW(SP, fcw); PUSHW(SP, Z->op[0]);
        Z->pc = GET_PC(SYSCALL); Z->irq_req &= ~Z8000_SYSCALL; CHANGE_FCW(GET_FCW(SYSCALL));
    } else if (Z->irq_req & Z8000_NMI) {
        Z->irq_vec = 0xffff; Z->halt = 0;
        CHANGE_FCW(fcw | F_S_N); PUSH_PC(); PUSHW(SP, fcw); PUSHW(SP, Z->irq_vec);
        Z->pc = GET_PC(NMI); Z->irq_req &= ~Z8000_NMI; CHANGE_FCW(GET_FCW(NMI));
    } else if ((Z->irq_req & Z8000_VI) && (Z->fcw & F_VIE)) {
        Z->irq_vec = 0xffff; Z->halt = 0;
        CHANGE_FCW(fcw | F_S_N); PUSH_PC(); PUSHW(SP, fcw); PUSHW(SP, Z->irq_vec);
        Z->pc = RDMEM_W(0, VEC00 + 2 * (Z->irq_vec & 0xff)); Z->irq_req &= ~Z8000_VI; CHANGE_FCW(GET_FCW(VI));
    } else if ((Z->irq_req & Z8000_NVI) && (Z->fcw & F_NVIE)) {
        Z->irq_vec = 0xffff; Z->halt = 0;
        CHANGE_FCW(fcw | F_S_N); PUSH_PC(); PUSHW(SP, fcw); PUSHW(SP, Z->irq_vec);
        Z->pc = GET_PC(NVI); Z->irq_req &= ~Z8000_NVI; CHANGE_FCW(GET_FCW(NVI));
    }
}

z8k_t *z8k_live(void) { return &Zs; }

void z8k_init_tables(void)
{
    for (int i = 0; i < 256; i++)
        z8000_zsp[i] = (uint8_t)(((i == 0) ? F_Z : 0) | ((i & 128) ? F_S : 0) |
                       ((((i>>7)^(i>>6)^(i>>5)^(i>>4)^(i>>3)^(i>>2)^(i>>1)^i) & 1) ? 0 : F_PV));
}

void z8k_reset(z8k_t *cpu)
{
    memset(cpu, 0, sizeof(*cpu));
    cpu->irq_req = Z8000_RESET;
}

void z8k_set_nvi(z8k_t *cpu, int state)
{
    cpu->irq_state[0] = state;
    if (state == CLEAR_LINE) { if (!(cpu->fcw & F_NVIE)) cpu->irq_req &= ~Z8000_NVI; }
    else { if (cpu->fcw & F_NVIE) cpu->irq_req |= Z8000_NVI; }
}

Z8K_HOT int z8k_run(z8k_t *cpu, int cycles_to_run)
{
    Zs = *cpu;
    Z->icount = cycles_to_run;
    const uint16_t *const *rp = z8k_rpage;
    do {
        if (__builtin_expect(Z->irq_req | Z->irq_state[0] | Z->halt, 0)) {
            /* an NVI asserted while NVIE was clear becomes pending when it is enabled */
            if (Z->irq_state[0] && (Z->fcw & F_NVIE)) Z->irq_req |= Z8000_NVI;
            if (Z->irq_req) Interrupt();
            if (Z->halt) { Z->icount = 0; break; }
        }
        uint32_t pc = Z->pc;
        uint16_t op = rp[(pc >> 8) & 0xff][(pc & 0xff) >> 1];
        Z->pc = pc + 2;
        Z->op[0] = op;
        Z->op_valid = 1;
        unsigned idx = Z8000_EXEC(op);
#ifdef Z8K_PROFILE
        z8k_op_count[idx]++;
#endif
        Z->icount -= z8000_exec_cyc[idx];
        z8000_exec_fn[idx]();
    } while (Z->icount > 0);
    *cpu = Zs;
    return cycles_to_run - Z->icount;
}
'''

# exec table: build at generation time
entries = re.findall(r'\{\s*(0x[0-9a-fA-F]+),\s*(0x[0-9a-fA-F]+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(\w+)\s*\}', tbl)
exec_tbl = [0] * 0x10000
for i, (beg, end, step, size, cyc, name) in enumerate(entries):
    b, e, st = int(beg, 16), int(end, 16), int(step)
    for v in range(b, e + 1, st):
        exec_tbl[v] = i
blocks = {}; idx = []
for i in range(0, 0x10000, 16):
    t = tuple(exec_tbl[i:i+16])
    if t not in blocks: blocks[t] = len(blocks)
    idx.append(blocks[t])
blk_list = sorted(blocks.items(), key=lambda kv: kv[1])
exec_c = 'static Z8K_DATA uint16_t z8000_exec_idx[0x1000] = {\n' + '\n'.join('    ' + ','.join(str(x) for x in idx[i:i+32]) + ',' for i in range(0, 0x1000, 32)) + '\n};\n'
exec_c += 'static Z8K_DATA uint16_t z8000_exec_blk[%d] = {\n' % (len(blk_list) * 16) + '\n'.join('    ' + ','.join(str(x) for x in t) + ',' for t, _ in blk_list) + '\n};\n'
print(f'dispatch: {len(blk_list)} blocks, {len(blk_list) * 32 + 0x1000 * 2} bytes in RAM')

names_c = '#ifdef Z8K_PROFILE\nstatic const char *const op_names[] = {\n' + ',\n'.join('    "%s"' % n for (_, _, _, _, _, n) in entries) + '\n};\nconst char *z8k_op_name(int i) { return (i >= 0 && i < %d) ? op_names[i] : "?"; }\n#endif\n' % len(entries)
fn_c = 'static Z8K_DATA opcode_func_t z8000_exec_fn[%d] = {\n' % len(entries) + '\n'.join('    ' + ','.join(n for (_, _, _, _, _, n) in entries[i:i+8]) + ',' for i in range(0, len(entries), 8)) + '\n};\n'
fn_c += 'static Z8K_DATA uint16_t z8000_exec_cyc[%d] = {\n' % len(entries) + '\n'.join('    ' + ','.join(c for (_, _, _, _, c, _) in entries[i:i+32]) + ',' for i in range(0, len(entries), 32)) + '\n};\n'
out.write_text(header + protos + '\n\n' + ops + '\n' + interrupt + '\n' + exec_c + fn_c + names_c)
print(f'wrote {out}: {len(entries)} table entries, {len(set(names))} opcode functions')
